name = "E. P. Ellyson"
license = "MIT"
licenselink = "https://github.com/reubenlillie/epellyson/blob/master/LICENSE"
description = "A Hugo theme for the electronic Manual of the Church of the Nazarene"
homepage = "https://github.com/reubenlillie/epellyson"
tags = ["responsive", "clean", "minimalist", "light", "multilingual", "product"]
features = []
min_version = "0.41"

[author]
  name = "Reuben L. Lillie"
  homepage = "https://github.com/reubenlillie"
